### ISSUE TITLE
Error: Cannot find module '/server/startup/i18n'

### ISSUE THREAD

**Issue by shahrukh-alizai** [reactioncommerce/reaction-example-plugin#34]
**Preconditions:**

```
Node: 8.11.3
NPM: 6.3.0
Meteor Node: 8.11.3
Meteor NPM: 5.10.0
Reaction CLI: 0.29.0
Docker: 18.06.1-ce
OS: Ubuntu 18.04
```

**Steps to reproduce:**

1. Install fresh Reaction Commerce. 
2. Clone reaction-example-plugin in /imports/plugins/custom.
3. Run `reaction reset` command on root.
4. Run `reaction` command.

**Expected result:**
Everything works fine.

**Actual result:**
```
in the root directory of your application.
/home/shahrukh/.meteor/packages/meteor-tool/.1.7.0_3.u9lhms.hf7k++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
						throw(ex);
						^

Error: Cannot find module '/server/startup/i18n'
    at makeMissingError (packages/modules-runtime.js:231:12)
    at require (packages/modules-runtime.js:241:19)
    at index.js (imports/plugins/custom/reaction-example-plugin/server/i18n/index.js:1:35)
    at fileEvaluate (packages/modules-runtime.js:339:7)
    at require (packages/modules-runtime.js:238:16)
    at index.js (imports/plugins/custom/reaction-example-plugin/server/index.js:1:14)
    at fileEvaluate (packages/modules-runtime.js:339:7)
    at require (packages/modules-runtime.js:238:16)
    at plugins.js (server/plugins.js:1:2604)
    at fileEvaluate (packages/modules-runtime.js:339:7)
    at require (packages/modules-runtime.js:238:16)
    at /home/shahrukh/nodeApps/rc102/.meteor/local/build/programs/server/app/app.js:90711:1
    at /home/shahrukh/nodeApps/rc102/.meteor/local/build/programs/server/boot.js:411:36
    at Array.forEach (<anonymous>)
    at /home/shahrukh/nodeApps/rc102/.meteor/local/build/programs/server/boot.js:220:19
    at /home/shahrukh/nodeApps/rc102/.meteor/local/build/programs/server/boot.js:471:5
=> Exited with code: 1

```

**Comment by shahrukh-alizai** [comment]
PR #35 is opened to resolve this issue with Reaction v1.15.0
